In [2]:
from pynq import Overlay
from pynq import PL
ol = Overlay("PynqInverceMatrix2.bit")
ol.download()
print(PL.ip_dict)

{'SEG_axi_fifo_mm_s_0_Mem0': [1136656384, 65536, None]}


In [3]:
import random
import invmat
import numpy as np

MATSIZE = 2
NUMELEMENTS = MATSIZE*MATSIZE

REPEAT = 2

inv_mat = invmat.InvMat(MATSIZE)

for i in range(REPEAT):
    # IP uses 16bit fixed point with 8 fractional bits, so -10 to 10 is appropriate
    m = np.array([random.uniform(-10, 10) for i in range(NUMELEMENTS)])
    m = m.reshape(MATSIZE, MATSIZE)
    print("mat:\n", m)
    print()
    
    # get the inverce matrix by numpy
    np_inv = np.linalg.inv(m)
    print("inv mat by numpy:\n", np_inv)
    print()
    
    # get the inverce matrix by IP
    m_inv = inv_mat.inv(m.reshape(-1))
    m_inv = np.array(m_inv)
    m_inv = m_inv.reshape(MATSIZE, MATSIZE)
    print("inv mat by IP:\n", m_inv)
    print()
    
    prod = m.dot(m_inv)
    print("mat * inv_mat_by_IP:\n", prod)
    print()


mat:
 [[-3.6245542   7.82069909]
 [-6.05252606  9.67271814]]

inv mat by numpy:
 [[ 0.78795694 -0.63708815]
 [ 0.49304961 -0.29526268]]

inv mat by IP:
 [[ 0.78515625 -0.6328125 ]
 [ 0.4921875  -0.29296875]]

mat * inv_mat_by_IP:
 [[ 1.00340895  0.00244277]
 [ 0.0086123   0.99631   ]]

mat:
 [[-2.91746271 -6.0996047 ]
 [ 6.64118165 -1.42584344]]

inv mat by numpy:
 [[-0.03192061  0.13655293]
 [-0.14867731 -0.06531375]]

inv mat by IP:
 [[-0.03125    0.1328125]
 [-0.1484375 -0.0625   ]]

mat * inv_mat_by_IP:
 [[ 0.99658078 -0.00625022]
 [ 0.00411171  0.97114715]]



In [4]:
from pynq import Overlay
from pynq import PL
ol = Overlay("PynqInverceMatrix3.bit")
ol.download()
print(PL.ip_dict)

{'SEG_axi_fifo_mm_s_0_Mem0': [1136656384, 65536, None]}


In [5]:
import random
import invmat
import numpy as np

MATSIZE = 3
NUMELEMENTS = MATSIZE*MATSIZE

REPEAT = 2

inv_mat = invmat.InvMat(MATSIZE)

for i in range(REPEAT):
    # IP uses 16bit fixed point with 8 fractional bits, so -10 to 10 is appropriate
    m = np.array([random.uniform(-10, 10) for i in range(NUMELEMENTS)])
    m = m.reshape(MATSIZE, MATSIZE)
    print("mat:\n", m)
    print()
    
    # get the inverce matrix by numpy
    np_inv = np.linalg.inv(m)
    print("inv mat by numpy:\n", np_inv)
    print()
    
    # get the inverce matrix by IP
    m_inv = inv_mat.inv(m.reshape(-1))
    m_inv = np.array(m_inv)
    m_inv = m_inv.reshape(MATSIZE, MATSIZE)
    print("inv mat by IP:\n", m_inv)
    print()
    
    prod = m.dot(m_inv)
    print("mat * inv_mat_by_IP:\n", prod)
    print()


mat:
 [[-9.27232032  5.31074801 -4.62328645]
 [-1.40608787 -0.19825161 -5.8636628 ]
 [-1.32642817 -4.71950642  8.75759408]]

inv mat by numpy:
 [[-0.08404376 -0.07055536 -0.09160863]
 [ 0.05741555 -0.2495773  -0.13679426]
 [ 0.0182122  -0.14518466  0.0265925 ]]

inv mat by IP:
 [[-0.0859375  -0.06640625 -0.08984375]
 [ 0.05078125 -0.24609375 -0.140625  ]
 [ 0.015625   -0.14453125  0.0234375 ]]

mat * inv_mat_by_IP:
 [[ 0.9942876  -0.0229925  -0.02212219]
 [ 0.01914848  0.98964402  0.01677774]
 [ 0.01116489 -0.01622187  0.98810798]]

mat:
 [[-0.48673532  7.45713934 -9.50950323]
 [-7.56053898  3.30048875 -7.27254833]
 [ 6.50529601 -3.60493491  9.51473817]]

inv mat by numpy:
 [[ 0.04112457 -0.29079032 -0.18116236]
 [ 0.19527757  0.45381763  0.54204365]
 [ 0.04586941  0.37075745  0.43433111]]

inv mat by IP:
 [[ 0.04296875 -0.28515625 -0.17578125]
 [ 0.1875      0.44140625  0.53125   ]
 [ 0.0390625   0.36328125  0.42578125]]

mat * inv_mat_by_IP:
 [[ 1.00583425 -0.02420069 -0.00180395]
 [